In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [86]:
def H_matrix(λ):
    H =np.array( [[1/2, 3*λ/4, 3*λ/(np.sqrt(2)), 0], [0, 3/2 + 15*λ/4 , 0 , 3* np.sqrt(3/2)*λ], [3*λ/(np.sqrt(2)),0,5/2 + 27*λ/4 ,0], [0,3* np.sqrt(3/2)*λ,0, 7/2 + 15*λ/4]])

    return H


In [87]:
def norms(A):
    n = A.shape[0]
    m = A.shape[1]
    norm_ = 0
    for i in range(n):
        for j in range(m):
            norm_ += A[i][j]*A[i][j]

    return np.sqrt(norm_)


In [88]:
H_inv = np.linalg.inv(H_matrix(0.4))

condition_no = norms(H_matrix(0.4)) * norms(H_inv)
condition_no



23.857566675696937

In [90]:
np.linalg.cond(H_matrix(0.4),'fro')

23.857566675696933

In [77]:
def norm(B):
    norm_ = 0
    for i in range(B.shape[0]):
        norm_ = norm_ + B[i]*B[i]
    return np.sqrt(norm_)


def QR(AB):
    Q = np.zeros([AB.shape[0], AB.shape[0]])

    Q[:, 0] = AB[:, 0]
    B = AB[:, 0]
    B = (1/norm(B)) * B
    Q[:, 0] = B

    n = 3
    for i in range(1, n+1):
        B = AB[:, i]
        temp = np.zeros(AB.shape[0])

        for j in range(0, i):  # Gram Schmidt Orthogonalization
            Proj = Q[:, j].dot(B)
            temp = temp + Proj * Q[:, j]

        B = B-temp
        B = B/norm(B)
        Q[:, i] = B

    Q=-Q

    R=np.linalg.inv(Q).dot(AB)

    

    return Q,R


In [95]:
H=H_matrix(0.4).copy()
w=np.eye(4)
for i in range(1,100):
    Q,R= QR(H)
    w=w.dot(Q)
    H=R.dot(Q)


H

array([[ 5.34849955e+000,  2.41791249e-002, -4.51880580e-002,
        -6.92867018e-003],
       [ 9.00953012e-015,  5.77763888e+000,  1.25171392e-002,
        -1.37797187e-001],
       [ 1.63101822e-054,  5.65887672e-041,  2.22236112e+000,
         2.61114265e-001],
       [ 1.00088768e-115,  4.35020267e-102,  1.43820469e-061,
         3.51500450e-001]])

In [97]:
w

array([[-1.72388358e-01, -2.50807122e-02,  1.36115668e-01,
        -9.75256754e-01],
       [-9.80411603e-15, -4.67532054e-01,  8.73764689e-01,
         1.33974055e-01],
       [-9.85029063e-01,  4.38933526e-03, -2.38213850e-02,
         1.70678122e-01],
       [-1.85435859e-14, -8.83609342e-01, -4.66304981e-01,
        -4.23579354e-02]])

In [94]:
np.linalg.eig(H_matrix(0.4))

(array([0.35150045, 5.34849955, 2.22236112, 5.77763888]),
 array([[-0.98502906,  0.17238836,  0.13369257, -0.03473854],
        [ 0.        ,  0.        ,  0.87531353, -0.46679171],
        [ 0.17238836,  0.98502906, -0.03809794, -0.05102952],
        [ 0.        ,  0.        , -0.4631426 , -0.88221013]]))