In [49]:
import numpy as np
import scipy.linalg

In [50]:
A=np.array([[3.0,5,6],[5,8,2],[6,2,8]])
A

array([[3., 5., 6.],
       [5., 8., 2.],
       [6., 2., 8.]])

In [51]:
import numpy as np

def norm(B):
    norm_=0
    for i in range(B.shape[0]):
        norm_= norm_ + B[i]*B[i]
    return np.sqrt(norm_)


def QR(AB):
    Q=np.zeros([AB.shape[0],AB.shape[0]])

    Q[:, 0] = AB[:, 0]
    B=AB[:,0]
    B=(1/norm(B)) * B
    Q[:,0]=B


    n=3
    for i in range(1,n):
        B=AB[:,i]
        temp=np.zeros(AB.shape[0])

        for j in range(0,i):                    #Gram Schmidt Orthogonalization
            Proj=Q[:,j].dot(B)
            temp=temp+ Proj* Q[:,j]
        
        B=B-temp
        B=B/norm(B)
        Q[:,i]=B

    
    R=np.linalg.inv(Q).dot(AB)

    return Q, R











In [71]:
def eigvalvecqr(A):
    B=np.eye(A.shape[0])
    D=A.copy()

    for i in range(0,1000):
        Q,R=QR(D)
        B=B.dot(Q.copy())
        D=R.dot(Q)

    
    return D.diagonal(),B


    
    


In [72]:
eigvalvecqr(A)

(array([15.04569484,  6.02738727, -2.07308211]),
 array([[ 0.54372909, -0.03859178, -0.83837304],
        [ 0.56263089,  0.75798656,  0.33000432],
        [ 0.62274004, -0.65112752,  0.43385227]]))