In [35]:
import numpy as np
import scipy as sc
import scipy.linalg

In [36]:
A=np.array([[5,5,],[-1,7]])

In [37]:
def svd(A):

    K=np.transpose(A).dot(A)

    eigval,vec=np.linalg.eig(K)

    sigma=np.zeros([A.shape[0],A.shape[0]])

    n=A.shape[0]
    for i in range (0,n):
        sigma[i][i]=np.sqrt(eigval[i])

    
    U=A.dot(vec).dot(np.linalg.inv(sigma))
    

    return U,sigma,np.transpose(vec)

In [38]:
svd(A)

(array([[-0.70710678, -0.70710678],
        [ 0.70710678, -0.70710678]]),
 array([[4.47213595, 0.        ],
        [0.        , 8.94427191]]),
 array([[-0.9486833 ,  0.31622777],
        [-0.31622777, -0.9486833 ]]))